create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports -filter { NAME =~  "*clk*" && DIRECTION == "IN" }]



set_property PACKAGE_PIN E3 [get_ports p_clk_sys]
set_property PACKAGE_PIN U9 [get_ports p_reset_sys]
set_property PACKAGE_PIN R8 [get_ports p_act_ok]
set_property PACKAGE_PIN R10 [get_ports p_act_out]
set_property PACKAGE_PIN V9 [get_ports p_CNN_finished_sys]
set_property PACKAGE_PIN T8 [get_ports p_CNN_ready_sys]
set_property PACKAGE_PIN E16 [get_ports p_CNN_start_sys]
set_property PACKAGE_PIN T16 [get_ports p_trigger_sys]
set_property PULLDOWN true [get_ports p_CNN_start_sys]
set_property PULLDOWN true [get_ports p_trigger_sys]
set_property PULLDOWN true [get_ports p_act_out]
set_property PULLDOWN true [get_ports p_CNN_finished_sys]
set_property PULLDOWN true [get_ports p_CNN_ready_sys]
set_property PULLDOWN true [get_ports p_act_ok]
set_property SLEW SLOW [get_ports p_act_ok]
set_property PACKAGE_PIN E18 [get_ports {p_act[15]}]
set_property PACKAGE_PIN D18 [get_ports {p_act[14]}]
set_property PACKAGE_PIN C17 [get_ports {p_act[13]}]
set_property PACKAGE_PIN G13 [get_ports {p_act[12]}]
set_property PACKAGE_PIN E17 [get_ports {p_act[11]}]
set_property PACKAGE_PIN D17 [get_ports {p_act[10]}]
set_property PACKAGE_PIN F14 [get_ports {p_act[9]}]
set_property PACKAGE_PIN B13 [get_ports {p_act[8]}]
set_property PACKAGE_PIN U11 [get_ports {p_act[7]}]
set_property PACKAGE_PIN T9 [get_ports {p_act[6]}]
set_property PACKAGE_PIN R16 [get_ports {p_act[5]}]
set_property PACKAGE_PIN K16 [get_ports {p_act[4]}]
set_property PACKAGE_PIN V15 [get_ports {p_act[3]}]
set_property PACKAGE_PIN V11 [get_ports {p_act[2]}]
set_property PACKAGE_PIN P15 [get_ports {p_act[1]}]
set_property PACKAGE_PIN G14 [get_ports {p_act[0]}]
set_property PULLDOWN true [get_ports {p_act[15]}]
set_property PULLDOWN true [get_ports {p_act[14]}]
set_property PULLDOWN true [get_ports {p_act[13]}]
set_property PULLDOWN true [get_ports {p_act[12]}]
set_property PULLDOWN true [get_ports {p_act[11]}]
set_property PULLDOWN true [get_ports {p_act[10]}]
set_property PULLDOWN true [get_ports {p_act[9]}]
set_property PULLDOWN true [get_ports {p_act[8]}]
set_property PULLDOWN true [get_ports {p_act[7]}]
set_property PULLDOWN true [get_ports {p_act[6]}]
set_property PULLDOWN true [get_ports {p_act[5]}]
set_property PULLDOWN true [get_ports {p_act[4]}]
set_property PULLDOWN true [get_ports {p_act[3]}]
set_property PULLDOWN true [get_ports {p_act[2]}]
set_property PULLDOWN true [get_ports {p_act[1]}]
set_property PULLDOWN true [get_ports {p_act[0]}]
set_property PULLDOWN true [get_ports p_reset_sys]
set_property PULLDOWN true [get_ports p_clk_sys]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p_act[12]}]

set_property IOSTANDARD LVCMOS33 [get_ports p_clk_sys]
set_property IOSTANDARD LVCMOS33 [get_ports p_reset_sys]
set_property IOSTANDARD LVCMOS33 [get_ports p_act_ok]
set_property IOSTANDARD LVCMOS33 [get_ports p_trigger_sys]
set_property IOSTANDARD LVCMOS33 [get_ports p_act_out]
set_property IOSTANDARD LVCMOS33 [get_ports p_CNN_finished_sys]
set_property IOSTANDARD LVCMOS33 [get_ports p_CNN_ready_sys]
set_property IOSTANDARD LVCMOS33 [get_ports p_CNN_start_sys]

set_property MARK_DEBUG false [get_nets {addra[0]}]
set_property MARK_DEBUG false [get_nets {addra[1]}]
set_property MARK_DEBUG false [get_nets {addra[2]}]
set_property MARK_DEBUG false [get_nets {addra[3]}]
set_property MARK_DEBUG false [get_nets {addra[4]}]
set_property MARK_DEBUG false [get_nets {addra[5]}]


set_property SLEW SLOW [get_ports p_CNN_ready_sys]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list p_clk_sys_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {EXT_BRAM_inst/addra[0]} {EXT_BRAM_inst/addra[1]} {EXT_BRAM_inst/addra[2]} {EXT_BRAM_inst/addra[3]} {EXT_BRAM_inst/addra[4]} {EXT_BRAM_inst/addra[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {EXT_GOLD_BRAM_inst/addra[0]} {EXT_GOLD_BRAM_inst/addra[1]} {EXT_GOLD_BRAM_inst/addra[2]} {EXT_GOLD_BRAM_inst/addra[3]} {EXT_GOLD_BRAM_inst/addra[4]} {EXT_GOLD_BRAM_inst/addra[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {p_act_OBUF[0]} {p_act_OBUF[1]} {p_act_OBUF[2]} {p_act_OBUF[3]} {p_act_OBUF[4]} {p_act_OBUF[5]} {p_act_OBUF[6]} {p_act_OBUF[7]} {p_act_OBUF[8]} {p_act_OBUF[9]} {p_act_OBUF[10]} {p_act_OBUF[11]} {p_act_OBUF[12]} {p_act_OBUF[13]} {p_act_OBUF[14]} {p_act_OBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list p_act_ok_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list p_act_out_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list p_CNN_finished_sys_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list p_CNN_ready_sys_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list p_CNN_start_sys_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list p_reset_sys_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list p_trigger_sys_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets p_clk_sys_IBUF_BUFG]
